# This is a basic workflow to help you get started with Actions



name: CI


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_uhmi:
    runs-on: self-hosted
    steps:
      # Runs a single command using the runners shell
      - name: Run a test
        id: run
        run: |
           cd /home/kerken
           bash nocrlc.sh >> logcat.txt
